[package]
name = "mnesio-graph"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Bi-temporal property-graph view over the mnesio event log."
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"

[dependencies]
mnesio-core.workspace = true
tokio.workspace = true
serde.workspace = true
async-trait.workspace = true
tracing.workspace = true
anyhow.workspace = true
fjall.workspace = true
bincode.workspace = true
ulid.workspace = true
time.workspace = true
